CREATE DATABASE motos_online;
USE motos_online;

CREATE TABLE ENDERECO (
    CEP_ENDERECO VARCHAR(10),
    RUA_ENDERECO VARCHAR(100),
    ESTADO_ENDERECO VARCHAR(45),
    BAIRRO_ENDERECO VARCHAR(45),
    CIDADE_ENDERECO VARCHAR(45),
    PRIMARY KEY (CEP_ENDERECO)
);

CREATE TABLE SERVICOS (
    ID_SERVICO INT NOT NULL AUTO_INCREMENT,
    NOME_SERVICO VARCHAR(45) NOT NULL,
    VALOR_SERVICO DECIMAL(10, 2),
    TEMPO_SERVICO TIME,
    PRIMARY KEY (ID_SERVICO)
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    NOME_FUNCIONARIO VARCHAR(45) NOT NULL,
    CEP_FUNCIONARIO VARCHAR(10),
    COMPLEMENTO_FUNCIONARIO VARCHAR(100),
    CPF_FUNCIONARIO VARCHAR(14),
    RG_FUNCIONARIO VARCHAR(12),
    LOGIN_FUNCIONARIO VARCHAR(45),
    SENHA_FUNCIONARIO VARCHAR(45),
    EMAIL_FUNCIONARIO VARCHAR(100),
    DATA_NASCIMENTO_FUNCIONARIO DATE,
    TELEFONE_FUNCIONARIO VARCHAR(20),
    PRIMARY KEY (ID_FUNCIONARIO),
    FOREIGN KEY (CEP_FUNCIONARIO) REFERENCES ENDERECO(CEP_ENDERECO)
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME_CLIENTES VARCHAR(45) NOT NULL,
    CEP_CLIENTES VARCHAR(10),
    CPF_CLIENTES VARCHAR(14),
    RG_CLIENTES VARCHAR(12),
    LOGIN VARCHAR(45),
    SENHA_CLIENTES VARCHAR(45),
    EMAIL_CLIENTES VARCHAR(100),
    DATANASCIMENTO_CLIENTES DATE,
    TELEFONE_CLIENTES VARCHAR(20),
    PRIMARY KEY (ID_CLIENTE),
    FOREIGN KEY (CEP_CLIENTES) REFERENCES ENDERECO(CEP_ENDERECO)
);

CREATE TABLE FORNECEDORES (
    ID_FORNECEDORES INT NOT NULL AUTO_INCREMENT,
    NOME_FORNECEDORES VARCHAR(45) NOT NULL,
    CNPJ_FORNECEDORES VARCHAR(20) NOT NULL,
    TELEFONE_FORNECEDORES DECIMAL(10, 0) NOT NULL,
    PRIMARY KEY (ID_FORNECEDORES)
);

CREATE TABLE AGENDAMENTO (
    ID_AGENDAMENTO INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    DATA_DE_ATENDIMENTO_AGENDAMENTO DATE,
    HORARIO_DE_ATENDIMENTO_AGENDAMENTO TIME,
    ID_FUNCIONARIO INT NOT NULL,
    SERVICO_AGENDAMENTO INT NOT NULL,
    VALOR_AGENDAMENTO DECIMAL(10, 2),
    FORMA_DE_PAGAMENTO VARCHAR(45),
    PRIMARY KEY (ID_AGENDAMENTO),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
    FOREIGN KEY (SERVICO_AGENDAMENTO) REFERENCES SERVICOS(ID_SERVICO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTOS INT NOT NULL AUTO_INCREMENT,
    NOME_PRODUTOS VARCHAR(45) NOT NULL,
    VALOR_PRODUTOS DECIMAL(10, 2) NOT NULL,
    CATEGORIA_PRODUTOS VARCHAR(45) NOT NULL,
    ID_FORNECEDORES INT NOT NULL,
    PRIMARY KEY (ID_PRODUTOS),
    FOREIGN KEY (ID_FORNECEDORES) REFERENCES FORNECEDORES(ID_FORNECEDORES)
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT NOT NULL AUTO_INCREMENT,
    METODO_PAGAMENTO VARCHAR(45) NOT NULL,
    VALOR_PAGAMENTO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_PAGAMENTO)
);

CREATE TABLE VENDAS (
    ID_VENDA INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    HORA_VENDA TIME NOT NULL,
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_VENDA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);


